spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productmicroservice
    username: root
    password: aman1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
